/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package winepackage;

/**
 *
 * @author dimit
 */
public class CartBoxPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductBoxPanel
     */
    public CartBoxPanel() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartBoxPanel = new javax.swing.JPanel();
        cartBoxCont = new javax.swing.JPanel();
        cartTitle = new javax.swing.JLabel();
        cartInfo = new javax.swing.JLabel();
        cartPrice = new javax.swing.JLabel();
        cartPhoto = new javax.swing.JLabel();
        cartMinBtn = new javax.swing.JButton();
        cartPlusBtn = new javax.swing.JButton();
        cartNumbDisplay = new javax.swing.JTextField();
        cartSumPrice = new javax.swing.JLabel();

        cartBoxPanel.setBackground(new java.awt.Color(255, 255, 255));
        cartBoxPanel.setLayout(new javax.swing.BoxLayout(cartBoxPanel, javax.swing.BoxLayout.X_AXIS));

        cartBoxCont.setBackground(new java.awt.Color(255, 255, 255));

        cartTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cartTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartTitle.setText("Zero Sauvignon Blanc");

        cartInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cartInfo.setForeground(new java.awt.Color(51, 51, 51));
        cartInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartInfo.setText("Ξηρός, Ήπιος, Λευκός");

        cartPrice.setBackground(new java.awt.Color(0, 0, 0));
        cartPrice.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        cartPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartPrice.setText("10,60 €");

        cartPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/wineImage.png"))); // NOI18N
        cartPhoto.setText(" ");

        cartMinBtn.setBackground(new java.awt.Color(179, 110, 120));
        cartMinBtn.setText("-");

        cartPlusBtn.setBackground(new java.awt.Color(179, 110, 120));
        cartPlusBtn.setText("+");

        cartNumbDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cartNumbDisplay.setText(" 1");
        cartNumbDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartNumbDisplayActionPerformed(evt);
            }
        });

        cartSumPrice.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        cartSumPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartSumPrice.setText("150,60 €");

        javax.swing.GroupLayout cartBoxContLayout = new javax.swing.GroupLayout(cartBoxCont);
        cartBoxCont.setLayout(cartBoxContLayout);
        cartBoxContLayout.setHorizontalGroup(
            cartBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartBoxContLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(cartMinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartNumbDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cartSumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        cartBoxContLayout.setVerticalGroup(
            cartBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartBoxContLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(cartBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartBoxContLayout.createSequentialGroup()
                        .addComponent(cartInfo)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartBoxContLayout.createSequentialGroup()
                        .addGroup(cartBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartPhoto)
                            .addComponent(cartTitle))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartBoxContLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cartBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cartPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartMinBtn)
                    .addComponent(cartPlusBtn)
                    .addComponent(cartNumbDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartSumPrice))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cartBoxPanel.add(cartBoxCont);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cartBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cartBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cartNumbDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartNumbDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartNumbDisplayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartBoxCont;
    private javax.swing.JPanel cartBoxPanel;
    private javax.swing.JLabel cartInfo;
    private javax.swing.JButton cartMinBtn;
    private javax.swing.JTextField cartNumbDisplay;
    private javax.swing.JLabel cartPhoto;
    private javax.swing.JButton cartPlusBtn;
    private javax.swing.JLabel cartPrice;
    private javax.swing.JLabel cartSumPrice;
    private javax.swing.JLabel cartTitle;
    // End of variables declaration//GEN-END:variables
}
