package winepackage;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setResizable(false);
        setTitle("Wine E-Shop");
        setIconImage(new ImageIcon(getClass().getResource("images/wine.png")).getImage());
        
        makeLabelClickable(wineTitle, 1, "Wine Title");
        makeLabelClickable(redWine, 2, "Red Wine");
        makeLabelClickable(roseWine, 3, "Rose Wine");
        makeLabelClickable(whiteWine, 4, "White Wine");
        makeLabelClickable(homeLogo, 5, "Home");
        makeLabelClickable(contactTitle, 6, "Contact");
        makeLabelClickable(aboutTitle, 7, "About");
        makeLabelClickable(accountIcon, 8, "Account");
        makeLabelClickable(cartIcon, 9, "Cart");
        makeLabelClickable(heartIcon, 10, "Favorites");
        
        hideAllPanels();
        homePanel.setVisible(true); // Show home by default
    }
    
    private void makeLabelClickable(JLabel label, int actionCode, String name) {
        label.setCursor(new Cursor(Cursor.HAND_CURSOR));
            //label.setForeground(new Color(115, 1, 18));
            label.setForeground(Color.WHITE);

        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println(name + " clicked! Action code: " + actionCode);

                // Future actions based on the action code
                switch (actionCode) {
                    case 1:
                        // action for wineTitle
                        System.out.println("Go to main wine page");
                        break;
                    case 2:
                        // red wine
                        System.out.println("Show red wine catalog");
                        break;
                    case 3:
                        // rose wine
                        System.out.println("Show rose wine catalog");
                        break;
                    case 4:
                        // white wine
                        System.out.println("Show white wine catalog");
                        break;
                    case 5:
                        System.out.println("Navigate to homepage");
                        break;
                    case 6:
                        System.out.println("Open contact section");
                        break;
                    case 7:
                        System.out.println("Open about section");
                        break;
                    case 8:
                        System.out.println("Open account/login screen");
                        break;
                    case 9:
                        System.out.println("Show cart");
                        break;
                    case 10:
                        System.out.println("Show favorites");
                        break;
                    default:
                        System.out.println("Unknown action");
                }
            }
        });
    }
    private void hideAllPanels() {
        homePanel.setVisible(false);
        winePanel.setVisible(false);
        redPanel.setVisible(false);
        rosePanel.setVisible(false);
        whitePanel.setVisible(false);
        contactPanel.setVisible(false);
        aboutPanel.setVisible(false);
        heartPanel.setVisible(false);
        cartPanel.setVisible(false);
        accountPanel.setVisible(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        homePanel = new javax.swing.JPanel();
        homeTitle = new javax.swing.JLabel();
        whiteBest = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jLabel135 = new javax.swing.JLabel();
        redBest = new javax.swing.JPanel();
        jPanel73 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jLabel139 = new javax.swing.JLabel();
        roseBest = new javax.swing.JPanel();
        jPanel75 = new javax.swing.JPanel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jLabel143 = new javax.swing.JLabel();
        backgroundImg = new javax.swing.JLabel();
        contactPanel = new javax.swing.JPanel();
        contactContent = new javax.swing.JPanel();
        msgTitle1 = new javax.swing.JLabel();
        msgTitle2 = new javax.swing.JLabel();
        fullnameBax = new javax.swing.JTextField();
        fullnameMsg = new javax.swing.JLabel();
        emailMsg = new javax.swing.JLabel();
        emailBox = new javax.swing.JTextField();
        subtitleMsg = new javax.swing.JLabel();
        messageBox = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        contTitle = new javax.swing.JLabel();
        topImage = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        aboutUsTitle = new javax.swing.JLabel();
        ourPhotoAboutUs = new javax.swing.JLabel();
        aboutBackground = new javax.swing.JLabel();
        heartPanel = new javax.swing.JPanel();
        titleWishlist = new javax.swing.JLabel();
        wishlistScrollPane = new javax.swing.JScrollPane();
        productContainerPanel = new javax.swing.JPanel();
        cartPanel = new javax.swing.JPanel();
        cartScrollPane = new javax.swing.JScrollPane();
        cartContainerPanel = new javax.swing.JPanel();
        cartInfoPanel = new javax.swing.JPanel();
        infoTitle = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        surename = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        postalCode = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        pricesPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        subtotalLb = new javax.swing.JLabel();
        shippingLb = new javax.swing.JLabel();
        totalLb = new javax.swing.JLabel();
        subtotalPrice = new javax.swing.JLabel();
        shippingPrice = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        submitCartBtn = new javax.swing.JButton();
        accountPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        phoneLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        emailInfo = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        profileInfoTitle = new javax.swing.JLabel();
        topImageProfile = new javax.swing.JLabel();
        winePanel = new javax.swing.JPanel();
        redWinePanel = new javax.swing.JPanel();
        redTextLine1 = new javax.swing.JLabel();
        redTextLine2 = new javax.swing.JLabel();
        redTextLine3 = new javax.swing.JLabel();
        redBackground = new javax.swing.JLabel();
        whiteWinePanel = new javax.swing.JPanel();
        whiteTextLine1 = new javax.swing.JLabel();
        whiteTextLine2 = new javax.swing.JLabel();
        whiteTextLine3 = new javax.swing.JLabel();
        whiteBackground = new javax.swing.JLabel();
        roseWinePanel = new javax.swing.JPanel();
        roseTextLine1 = new javax.swing.JLabel();
        roseTextLine2 = new javax.swing.JLabel();
        roseTextLine3 = new javax.swing.JLabel();
        roseBackground = new javax.swing.JLabel();
        winePageTitle = new javax.swing.JLabel();
        winePageBackground = new javax.swing.JLabel();
        redPanel = new javax.swing.JPanel();
        redTitle = new javax.swing.JLabel();
        redScrollPane = new javax.swing.JScrollPane();
        paddingPanel = new javax.swing.JPanel();
        redContainerPanel = new javax.swing.JPanel();
        redWineBackground = new javax.swing.JLabel();
        rosePanel = new javax.swing.JPanel();
        roseTitle = new javax.swing.JLabel();
        roseScrollPane = new javax.swing.JScrollPane();
        paddingPanel1 = new javax.swing.JPanel();
        roseContainerPanel = new javax.swing.JPanel();
        roseWineBackground = new javax.swing.JLabel();
        whitePanel = new javax.swing.JPanel();
        whiteTitle = new javax.swing.JLabel();
        whiteScrollPane = new javax.swing.JScrollPane();
        paddingPanel2 = new javax.swing.JPanel();
        whiteContainerPanel = new javax.swing.JPanel();
        whiteWineBackground = new javax.swing.JLabel();
        topbarPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        accountIcon = new javax.swing.JLabel();
        cartIcon = new javax.swing.JLabel();
        heartIcon = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        sidebarPanel = new javax.swing.JPanel();
        homeLogo = new javax.swing.JLabel();
        wineTitle = new javax.swing.JLabel();
        redWine = new javax.swing.JLabel();
        roseWine = new javax.swing.JLabel();
        whiteWine = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        contactTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        aboutTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1166, 0));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(115, 1, 18));
        Background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 1170, 10));

        jSeparator5.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, -1, 10, 650));

        homePanel.setBackground(new java.awt.Color(153, 153, 255));
        homePanel.setLayout(null);

        homeTitle.setFont(new java.awt.Font("Serif", 3, 40)); // NOI18N
        homeTitle.setForeground(new java.awt.Color(255, 255, 255));
        homeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTitle.setText("Our Best Sellers");
        homePanel.add(homeTitle);
        homeTitle.setBounds(340, 300, 350, 40);

        whiteBest.setBackground(new java.awt.Color(255, 255, 255));

        jPanel71.setBackground(new java.awt.Color(255, 255, 255));

        jLabel128.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel128.setText("Zero Sauvignon Blanc");

        jLabel129.setForeground(new java.awt.Color(51, 51, 51));
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel129.setText("Ξηρός, Ήπιος, Λευκός");

        jLabel130.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel130.setText("10,60 €");

        jButton31.setBackground(new java.awt.Color(179, 110, 120));
        jButton31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton31.setText("Buy");

        jButton46.setBackground(new java.awt.Color(179, 110, 120));
        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton46.setText("♡");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel128, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel71Layout.createSequentialGroup()
                        .addComponent(jLabel130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel128)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel129)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel130)
                    .addComponent(jButton31)
                    .addComponent(jButton46))
                .addContainerGap())
        );

        jLabel135.setBackground(new java.awt.Color(255, 255, 255));
        jLabel135.setForeground(new java.awt.Color(255, 255, 255));
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/wineImage.png"))); // NOI18N
        jLabel135.setText(" ");

        javax.swing.GroupLayout whiteBestLayout = new javax.swing.GroupLayout(whiteBest);
        whiteBest.setLayout(whiteBestLayout);
        whiteBestLayout.setHorizontalGroup(
            whiteBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel71, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whiteBestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel135, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        whiteBestLayout.setVerticalGroup(
            whiteBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whiteBestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel135, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePanel.add(whiteBest);
        whiteBest.setBounds(430, 350, 170, 210);

        redBest.setBackground(new java.awt.Color(255, 255, 255));

        jPanel73.setBackground(new java.awt.Color(255, 255, 255));

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel136.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel136.setText("Zero Sauvignon Blanc");

        jLabel137.setForeground(new java.awt.Color(51, 51, 51));
        jLabel137.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel137.setText("Ξηρός, Ήπιος, Λευκός");

        jLabel138.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel138.setText("10,60 €");

        jButton33.setBackground(new java.awt.Color(179, 110, 120));
        jButton33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton33.setText("Buy");

        jButton35.setBackground(new java.awt.Color(179, 110, 120));
        jButton35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton35.setText("♡");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel73Layout = new javax.swing.GroupLayout(jPanel73);
        jPanel73.setLayout(jPanel73Layout);
        jPanel73Layout.setHorizontalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel136, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel137, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel73Layout.createSequentialGroup()
                        .addComponent(jLabel138)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel73Layout.setVerticalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel136)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel137)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel138)
                    .addComponent(jButton33)
                    .addComponent(jButton35))
                .addContainerGap())
        );

        jLabel139.setBackground(new java.awt.Color(255, 255, 255));
        jLabel139.setForeground(new java.awt.Color(255, 255, 255));
        jLabel139.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel139.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/wineImage.png"))); // NOI18N
        jLabel139.setText(" ");

        javax.swing.GroupLayout redBestLayout = new javax.swing.GroupLayout(redBest);
        redBest.setLayout(redBestLayout);
        redBestLayout.setHorizontalGroup(
            redBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel73, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redBestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        redBestLayout.setVerticalGroup(
            redBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redBestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel139, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePanel.add(redBest);
        redBest.setBounds(110, 350, 170, 210);

        roseBest.setBackground(new java.awt.Color(255, 255, 255));

        jPanel75.setBackground(new java.awt.Color(255, 255, 255));

        jLabel140.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel140.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel140.setText("Zero Sauvignon Blanc");

        jLabel141.setForeground(new java.awt.Color(51, 51, 51));
        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel141.setText("Ξηρός, Ήπιος, Λευκός");

        jLabel142.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel142.setText("10,60 €");

        jButton34.setBackground(new java.awt.Color(179, 110, 120));
        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton34.setText("Buy");

        jButton47.setBackground(new java.awt.Color(179, 110, 120));
        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton47.setText("♡");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel75Layout = new javax.swing.GroupLayout(jPanel75);
        jPanel75.setLayout(jPanel75Layout);
        jPanel75Layout.setHorizontalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel75Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel140, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel141, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel75Layout.createSequentialGroup()
                        .addComponent(jLabel142)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel75Layout.setVerticalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel140)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel141)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel142)
                    .addComponent(jButton34)
                    .addComponent(jButton47))
                .addContainerGap())
        );

        jLabel143.setBackground(new java.awt.Color(255, 255, 255));
        jLabel143.setForeground(new java.awt.Color(255, 255, 255));
        jLabel143.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/wineImage.png"))); // NOI18N
        jLabel143.setText(" ");

        javax.swing.GroupLayout roseBestLayout = new javax.swing.GroupLayout(roseBest);
        roseBest.setLayout(roseBestLayout);
        roseBestLayout.setHorizontalGroup(
            roseBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel75, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roseBestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel143, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roseBestLayout.setVerticalGroup(
            roseBestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roseBestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePanel.add(roseBest);
        roseBest.setBounds(750, 350, 170, 210);

        backgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/WINE_NOT__20250521_223250_0000.png"))); // NOI18N
        backgroundImg.setText(" ");
        homePanel.add(backgroundImg);
        backgroundImg.setBounds(0, 0, 1030, 580);

        Background.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        contactPanel.setBackground(new java.awt.Color(0, 153, 153));
        contactPanel.setLayout(null);

        contactContent.setBackground(new java.awt.Color(171, 1, 26));

        msgTitle1.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        msgTitle1.setForeground(new java.awt.Color(255, 255, 255));
        msgTitle1.setText("Let's Start a Convertation");

        msgTitle2.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        msgTitle2.setForeground(new java.awt.Color(255, 255, 255));
        msgTitle2.setText("Please note: all fields are required.");

        fullnameBax.setText(" ");
        fullnameBax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameBaxActionPerformed(evt);
            }
        });

        fullnameMsg.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        fullnameMsg.setForeground(new java.awt.Color(255, 255, 255));
        fullnameMsg.setText("Fullname:");

        emailMsg.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        emailMsg.setForeground(new java.awt.Color(255, 255, 255));
        emailMsg.setText("Email:");

        emailBox.setText("  ");
        emailBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBoxActionPerformed(evt);
            }
        });

        subtitleMsg.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        subtitleMsg.setForeground(new java.awt.Color(255, 255, 255));
        subtitleMsg.setText("Write the reason for contacting:");

        messageBox.setText("  ");

        submitBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(235, 4, 36));
        submitBtn.setText("Submit");

        javax.swing.GroupLayout contactContentLayout = new javax.swing.GroupLayout(contactContent);
        contactContent.setLayout(contactContentLayout);
        contactContentLayout.setHorizontalGroup(
            contactContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactContentLayout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addGroup(contactContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgTitle2)
                    .addComponent(msgTitle1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactContentLayout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addGroup(contactContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullnameBax, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailMsg)
                    .addComponent(fullnameMsg))
                .addGap(85, 85, 85)
                .addGroup(contactContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtitleMsg))
                .addGap(172, 172, 172))
            .addGroup(contactContentLayout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contactContentLayout.setVerticalGroup(
            contactContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactContentLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(msgTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgTitle2)
                .addGap(17, 17, 17)
                .addGroup(contactContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullnameMsg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subtitleMsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactContentLayout.createSequentialGroup()
                        .addComponent(fullnameBax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        contactPanel.add(contactContent);
        contactContent.setBounds(0, 290, 1030, 290);

        contTitle.setFont(new java.awt.Font("Noto Serif", 1, 48)); // NOI18N
        contTitle.setForeground(new java.awt.Color(255, 255, 255));
        contTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contTitle.setText("Contact Us");
        contactPanel.add(contTitle);
        contTitle.setBounds(340, 190, 340, 110);

        topImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/pexels-adrian-odogwu-2078202-3820514(1)(1).jpg"))); // NOI18N
        topImage.setText(" ");
        contactPanel.add(topImage);
        topImage.setBounds(0, 0, 1030, 290);

        Background.add(contactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        aboutPanel.setBackground(new java.awt.Color(171, 1, 26));
        aboutPanel.setLayout(null);

        aboutUsTitle.setFont(new java.awt.Font("Noto Serif", 1, 48)); // NOI18N
        aboutUsTitle.setForeground(new java.awt.Color(255, 255, 255));
        aboutUsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutUsTitle.setText("About Us");
        aboutPanel.add(aboutUsTitle);
        aboutUsTitle.setBounds(340, 150, 340, 110);

        ourPhotoAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/freepik__make-the-background-abstract-with-soft-pastel-colo__79196.png"))); // NOI18N
        ourPhotoAboutUs.setText(" ");
        aboutPanel.add(ourPhotoAboutUs);
        ourPhotoAboutUs.setBounds(280, 230, 450, 240);

        aboutBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/pexels-adrian-odogwu-2078202-3820514(1)(1).jpg"))); // NOI18N
        aboutBackground.setText(" ");
        aboutBackground.setPreferredSize(new java.awt.Dimension(1030, 290));
        aboutPanel.add(aboutBackground);
        aboutBackground.setBounds(0, 0, 1038, 290);

        Background.add(aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        heartPanel.setBackground(new java.awt.Color(171, 1, 26));

        titleWishlist.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        titleWishlist.setForeground(new java.awt.Color(255, 255, 255));
        titleWishlist.setText("Wishlist");

        for (int i = 0; i < 30; i++) {
            ProductBoxPanel box = new ProductBoxPanel();

            productContainerPanel.add(box);
        }
        productContainerPanel.revalidate();
        productContainerPanel.repaint();
        productContainerPanel.setLayout(new javax.swing.BoxLayout(productContainerPanel, javax.swing.BoxLayout.Y_AXIS));
        wishlistScrollPane.setViewportView(productContainerPanel);

        javax.swing.GroupLayout heartPanelLayout = new javax.swing.GroupLayout(heartPanel);
        heartPanel.setLayout(heartPanelLayout);
        heartPanelLayout.setHorizontalGroup(
            heartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heartPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(heartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleWishlist, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wishlistScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        heartPanelLayout.setVerticalGroup(
            heartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heartPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleWishlist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wishlistScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Background.add(heartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        cartPanel.setBackground(new java.awt.Color(255, 255, 255));

        cartScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        cartScrollPane.setForeground(new java.awt.Color(255, 255, 255));
        cartScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        for (int i = 0; i < 30; i++) {
            CartBoxPanel box = new CartBoxPanel();

            cartContainerPanel.add(box);
        }
        cartContainerPanel.revalidate();
        cartContainerPanel.repaint();
        cartContainerPanel.setLayout(new javax.swing.BoxLayout(cartContainerPanel, javax.swing.BoxLayout.Y_AXIS));
        cartScrollPane.setViewportView(cartContainerPanel);

        cartInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        cartInfoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        infoTitle.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        infoTitle.setText("Your information");

        firstname.setForeground(new java.awt.Color(102, 102, 102));
        firstname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstname.setText("Firstname");
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        surename.setForeground(new java.awt.Color(102, 102, 102));
        surename.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        surename.setText("Surename");
        surename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surenameActionPerformed(evt);
            }
        });

        phoneNumber.setForeground(new java.awt.Color(102, 102, 102));
        phoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneNumber.setText("Phone Number");
        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });

        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email.setText("Email");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        address.setForeground(new java.awt.Color(102, 102, 102));
        address.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        address.setText("Address");
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        postalCode.setForeground(new java.awt.Color(102, 102, 102));
        postalCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        postalCode.setText("P. Code");
        postalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeActionPerformed(evt);
            }
        });

        city.setForeground(new java.awt.Color(102, 102, 102));
        city.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        city.setText("City");
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cartInfoPanelLayout = new javax.swing.GroupLayout(cartInfoPanel);
        cartInfoPanel.setLayout(cartInfoPanelLayout);
        cartInfoPanelLayout.setHorizontalGroup(
            cartInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoTitle)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartInfoPanelLayout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(surename, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartInfoPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(postalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        cartInfoPanelLayout.setVerticalGroup(
            cartInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cartInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cartInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pricesPanel.setBackground(new java.awt.Color(255, 255, 255));
        pricesPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        title.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        title.setText("Cart Summary");

        subtotalLb.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        subtotalLb.setText("Subtotal:");

        shippingLb.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        shippingLb.setText("Shipping:");

        totalLb.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        totalLb.setText("Total:");

        subtotalPrice.setFont(new java.awt.Font("Liberation Sans", 3, 19)); // NOI18N
        subtotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subtotalPrice.setText("36 €");

        shippingPrice.setFont(new java.awt.Font("Liberation Sans", 3, 19)); // NOI18N
        shippingPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shippingPrice.setText("3 €");

        totalPrice.setFont(new java.awt.Font("Liberation Sans", 3, 19)); // NOI18N
        totalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPrice.setText("39 €");

        submitCartBtn.setBackground(new java.awt.Color(179, 110, 120));
        submitCartBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        submitCartBtn.setText("SUBMIT");

        javax.swing.GroupLayout pricesPanelLayout = new javax.swing.GroupLayout(pricesPanel);
        pricesPanel.setLayout(pricesPanelLayout);
        pricesPanelLayout.setHorizontalGroup(
            pricesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pricesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pricesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pricesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pricesPanelLayout.createSequentialGroup()
                        .addComponent(subtotalLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subtotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pricesPanelLayout.createSequentialGroup()
                        .addComponent(shippingLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(shippingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pricesPanelLayout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pricesPanelLayout.createSequentialGroup()
                        .addComponent(totalLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        pricesPanelLayout.setVerticalGroup(
            pricesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(pricesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalLb)
                    .addComponent(subtotalPrice))
                .addGap(25, 25, 25)
                .addGroup(pricesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shippingLb)
                    .addComponent(shippingPrice))
                .addGap(26, 26, 26)
                .addGroup(pricesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLb)
                    .addComponent(totalPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitCartBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
        cartPanel.setLayout(cartPanelLayout);
        cartPanelLayout.setHorizontalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cartScrollPane)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pricesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        cartPanelLayout.setVerticalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addComponent(cartScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cartInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pricesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Background.add(cartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        accountPanel.setBackground(new java.awt.Color(40, 0, 6));
        accountPanel.setLayout(null);

        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/user(1).png"))); // NOI18N
        userIcon.setText("  ");
        accountPanel.add(userIcon);
        userIcon.setBounds(110, 130, 110, 102);

        username.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");
        accountPanel.add(username);
        username.setBounds(220, 160, 270, 50);

        phoneLabel.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        phoneLabel.setText("Τηλέφωνο:");

        nameLabel.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        nameLabel.setText("Ονοματεπώνυμο:");

        emailLabel.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        emailLabel.setText("Email:");

        fullname.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        fullname.setText("Όναμα Επώνημο");

        emailInfo.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        emailInfo.setText("exampleemail@email.com");

        phone.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        phone.setText("6901234567");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailInfo)
                            .addComponent(fullname)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phone)))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname))
                .addGap(42, 42, 42)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailInfo))
                .addGap(42, 42, 42)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        accountPanel.add(infoPanel);
        infoPanel.setBounds(110, 260, 810, 290);

        profileInfoTitle.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        profileInfoTitle.setForeground(new java.awt.Color(255, 255, 255));
        profileInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileInfoTitle.setText("Your Info");
        accountPanel.add(profileInfoTitle);
        profileInfoTitle.setBounds(440, 220, 130, 40);

        topImageProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/pexels-adrian-odogwu-2078202-3820514(1)(1).jpg"))); // NOI18N
        topImageProfile.setText("  ");
        accountPanel.add(topImageProfile);
        topImageProfile.setBounds(0, 0, 1030, 290);

        Background.add(accountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        winePanel.setBackground(new java.awt.Color(0, 204, 51));
        winePanel.setLayout(null);

        redWinePanel.setLayout(null);

        redTextLine1.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        redTextLine1.setForeground(new java.awt.Color(204, 0, 0));
        redTextLine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redTextLine1.setText("Check our ");
        redTextLine1.setToolTipText("");
        redTextLine1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        redTextLine1.setName(""); // NOI18N
        redWinePanel.add(redTextLine1);
        redTextLine1.setBounds(0, -10, 200, 70);

        redTextLine2.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        redTextLine2.setForeground(new java.awt.Color(204, 0, 0));
        redTextLine2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redTextLine2.setText("list of");
        redTextLine2.setToolTipText("");
        redTextLine2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        redTextLine2.setName(""); // NOI18N
        redWinePanel.add(redTextLine2);
        redTextLine2.setBounds(0, 30, 200, 70);

        redTextLine3.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        redTextLine3.setForeground(new java.awt.Color(204, 0, 0));
        redTextLine3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redTextLine3.setText("red wines");
        redTextLine3.setToolTipText("");
        redTextLine3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        redTextLine3.setName(""); // NOI18N
        redWinePanel.add(redTextLine3);
        redTextLine3.setBounds(0, 70, 200, 70);

        redBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image (2).png"))); // NOI18N
        redBackground.setText(" ");
        redWinePanel.add(redBackground);
        redBackground.setBounds(0, 0, 208, 210);

        winePanel.add(redWinePanel);
        redWinePanel.setBounds(420, 300, 200, 210);

        whiteWinePanel.setLayout(null);

        whiteTextLine1.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        whiteTextLine1.setForeground(new java.awt.Color(255, 255, 255));
        whiteTextLine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whiteTextLine1.setText("Check our ");
        whiteTextLine1.setToolTipText("");
        whiteTextLine1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        whiteTextLine1.setName(""); // NOI18N
        whiteWinePanel.add(whiteTextLine1);
        whiteTextLine1.setBounds(0, -10, 200, 70);

        whiteTextLine2.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        whiteTextLine2.setForeground(new java.awt.Color(255, 255, 255));
        whiteTextLine2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whiteTextLine2.setText("list of");
        whiteTextLine2.setToolTipText("");
        whiteTextLine2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        whiteTextLine2.setName(""); // NOI18N
        whiteWinePanel.add(whiteTextLine2);
        whiteTextLine2.setBounds(0, 30, 200, 70);

        whiteTextLine3.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        whiteTextLine3.setForeground(new java.awt.Color(255, 255, 255));
        whiteTextLine3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whiteTextLine3.setText("white wines");
        whiteTextLine3.setToolTipText("");
        whiteTextLine3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        whiteTextLine3.setName(""); // NOI18N
        whiteWinePanel.add(whiteTextLine3);
        whiteTextLine3.setBounds(0, 70, 200, 70);

        whiteBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whiteBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image (2).png"))); // NOI18N
        whiteBackground.setText(" ");
        whiteWinePanel.add(whiteBackground);
        whiteBackground.setBounds(0, 0, 208, 210);

        winePanel.add(whiteWinePanel);
        whiteWinePanel.setBounds(80, 300, 200, 210);

        roseWinePanel.setLayout(null);

        roseTextLine1.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        roseTextLine1.setForeground(new java.awt.Color(255, 153, 153));
        roseTextLine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roseTextLine1.setText("Check our ");
        roseTextLine1.setToolTipText("");
        roseTextLine1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roseTextLine1.setName(""); // NOI18N
        roseWinePanel.add(roseTextLine1);
        roseTextLine1.setBounds(0, -10, 200, 70);

        roseTextLine2.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        roseTextLine2.setForeground(new java.awt.Color(255, 153, 153));
        roseTextLine2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roseTextLine2.setText("list of");
        roseTextLine2.setToolTipText("");
        roseTextLine2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roseTextLine2.setName(""); // NOI18N
        roseWinePanel.add(roseTextLine2);
        roseTextLine2.setBounds(0, 30, 200, 70);

        roseTextLine3.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        roseTextLine3.setForeground(new java.awt.Color(255, 153, 153));
        roseTextLine3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roseTextLine3.setText("rose wines");
        roseTextLine3.setToolTipText("");
        roseTextLine3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roseTextLine3.setName(""); // NOI18N
        roseWinePanel.add(roseTextLine3);
        roseTextLine3.setBounds(0, 70, 200, 70);

        roseBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image (2).png"))); // NOI18N
        roseBackground.setText(" ");
        roseWinePanel.add(roseBackground);
        roseBackground.setBounds(0, 0, 208, 210);

        winePanel.add(roseWinePanel);
        roseWinePanel.setBounds(760, 300, 200, 210);

        winePageTitle.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        winePageTitle.setForeground(new java.awt.Color(255, 255, 255));
        winePageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winePageTitle.setText("Our Wines");
        winePanel.add(winePageTitle);
        winePageTitle.setBounds(380, 50, 290, 40);

        winePageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/WINE_NOT__20250521_223250_0000.png"))); // NOI18N
        winePageBackground.setText(" ");
        winePanel.add(winePageBackground);
        winePageBackground.setBounds(0, 0, 1030, 580);

        Background.add(winePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        redPanel.setBackground(new java.awt.Color(255, 255, 255));
        redPanel.setLayout(null);

        redTitle.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        redTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redTitle.setText("Red Wines");
        redPanel.add(redTitle);
        redTitle.setBounds(400, 10, 250, 50);

        redScrollPane.setBackground(new java.awt.Color(179, 110, 120));
        redScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        paddingPanel.setBackground(new java.awt.Color(255, 255, 255));
        paddingPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 0, 0));
        paddingPanel.setLayout(new java.awt.BorderLayout());

        redContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        redContainerPanel.setAutoscrolls(true);
        redContainerPanel.setMaximumSize(new java.awt.Dimension(180, 180));
        redContainerPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

        for (int i = 0; i < 20; i++) {
            ProductSquerePanel box = new ProductSquerePanel();
            redContainerPanel.add(box); // This is your JPanel inside JScrollPane
        }
        redContainerPanel.revalidate();
        redContainerPanel.repaint();
        redContainerPanel.setLayout(new java.awt.GridLayout(0, 4));
        paddingPanel.add(redContainerPanel, java.awt.BorderLayout.CENTER);

        redScrollPane.setViewportView(paddingPanel);

        redPanel.add(redScrollPane);
        redScrollPane.setBounds(40, 60, 940, 510);

        redWineBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/freepik__make-the-background-abstract-with-soft-pastel-colo__79196.png"))); // NOI18N
        redWineBackground.setText(" ");
        redPanel.add(redWineBackground);
        redWineBackground.setBounds(-6, -2, 1040, 580);

        Background.add(redPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        rosePanel.setBackground(new java.awt.Color(255, 255, 255));
        rosePanel.setLayout(null);

        roseTitle.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        roseTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roseTitle.setText("Rose Wines");
        rosePanel.add(roseTitle);
        roseTitle.setBounds(0, 10, 1030, 50);

        roseScrollPane.setBackground(new java.awt.Color(179, 110, 120));
        roseScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        paddingPanel1.setBackground(new java.awt.Color(255, 255, 255));
        paddingPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 0, 0));
        paddingPanel1.setLayout(new java.awt.BorderLayout());

        roseContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        roseContainerPanel.setAutoscrolls(true);
        roseContainerPanel.setMaximumSize(new java.awt.Dimension(180, 180));
        roseContainerPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

        for (int i = 0; i < 20; i++) {
            ProductSquerePanel box = new ProductSquerePanel();
            roseContainerPanel.add(box); // This is your JPanel inside JScrollPane
        }
        roseContainerPanel.revalidate();
        roseContainerPanel.repaint();
        roseContainerPanel.setLayout(new java.awt.GridLayout(0, 4));
        paddingPanel1.add(roseContainerPanel, java.awt.BorderLayout.CENTER);

        roseScrollPane.setViewportView(paddingPanel1);

        rosePanel.add(roseScrollPane);
        roseScrollPane.setBounds(40, 60, 940, 510);

        roseWineBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/freepik__make-the-background-abstract-with-soft-pastel-colo__79196.png"))); // NOI18N
        roseWineBackground.setText(" ");
        rosePanel.add(roseWineBackground);
        roseWineBackground.setBounds(-6, -2, 1040, 580);

        Background.add(rosePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        whitePanel.setBackground(new java.awt.Color(255, 255, 255));
        whitePanel.setLayout(null);

        whiteTitle.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        whiteTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whiteTitle.setText("White Wines");
        whitePanel.add(whiteTitle);
        whiteTitle.setBounds(0, 10, 1030, 50);

        whiteScrollPane.setBackground(new java.awt.Color(179, 110, 120));
        whiteScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        paddingPanel2.setBackground(new java.awt.Color(255, 255, 255));
        paddingPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 0, 0));
        paddingPanel2.setLayout(new java.awt.BorderLayout());

        whiteContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        whiteContainerPanel.setAutoscrolls(true);
        whiteContainerPanel.setMaximumSize(new java.awt.Dimension(180, 180));
        whiteContainerPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

        for (int i = 0; i < 20; i++) {
            ProductSquerePanel box = new ProductSquerePanel();
            whiteContainerPanel.add(box); // This is your JPanel inside JScrollPane
        }
        whiteContainerPanel.revalidate();
        whiteContainerPanel.repaint();
        whiteContainerPanel.setLayout(new java.awt.GridLayout(0, 4));
        paddingPanel2.add(whiteContainerPanel, java.awt.BorderLayout.CENTER);

        whiteScrollPane.setViewportView(paddingPanel2);

        whitePanel.add(whiteScrollPane);
        whiteScrollPane.setBounds(40, 60, 940, 510);

        whiteWineBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/freepik__make-the-background-abstract-with-soft-pastel-colo__79196.png"))); // NOI18N
        whiteWineBackground.setText(" ");
        whitePanel.add(whiteWineBackground);
        whiteWineBackground.setBounds(-6, -2, 1040, 580);

        Background.add(whitePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        topbarPanel.setBackground(new java.awt.Color(179, 110, 120));

        jSeparator2.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        accountIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/account.png"))); // NOI18N
        accountIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountIconMouseClicked(evt);
            }
        });

        cartIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/grocery-store.png"))); // NOI18N
        cartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartIconMouseClicked(evt);
            }
        });

        heartIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/heart.png"))); // NOI18N
        heartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heartIconMouseClicked(evt);
            }
        });

        searchField.setBackground(new java.awt.Color(254, 199, 207));
        searchField.setForeground(new java.awt.Color(255, 255, 255));
        searchField.setText("Search for the wines you want...");

        searchButton.setBackground(new java.awt.Color(252, 129, 147));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");

        jSeparator6.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout topbarPanelLayout = new javax.swing.GroupLayout(topbarPanel);
        topbarPanel.setLayout(topbarPanelLayout);
        topbarPanelLayout.setHorizontalGroup(
            topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topbarPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addGap(118, 118, 118)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(heartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        topbarPanelLayout.setVerticalGroup(
            topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topbarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addComponent(cartIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(topbarPanelLayout.createSequentialGroup()
                .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(topbarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heartIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topbarPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(accountIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Background.add(topbarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1030, 70));

        sidebarPanel.setBackground(new java.awt.Color(179, 110, 120));

        homeLogo.setBackground(new java.awt.Color(179, 110, 120));
        homeLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/home (3).png"))); // NOI18N
        homeLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLogoMouseClicked(evt);
            }
        });

        wineTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        wineTitle.setForeground(new java.awt.Color(255, 255, 255));
        wineTitle.setText("Wines");
        wineTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wineTitleMouseClicked(evt);
            }
        });

        redWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        redWine.setForeground(new java.awt.Color(255, 255, 255));
        redWine.setText("▸Red");
        redWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redWineMouseClicked(evt);
            }
        });

        roseWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        roseWine.setForeground(new java.awt.Color(255, 255, 255));
        roseWine.setText("▸Rose");
        roseWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roseWineMouseClicked(evt);
            }
        });

        whiteWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        whiteWine.setForeground(new java.awt.Color(255, 255, 255));
        whiteWine.setText("▸White");
        whiteWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteWineMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(115, 1, 18));

        contactTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        contactTitle.setForeground(new java.awt.Color(255, 255, 255));
        contactTitle.setText("Contact");
        contactTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contactTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactTitleMouseClicked(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(115, 1, 18));

        aboutTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        aboutTitle.setForeground(new java.awt.Color(255, 255, 255));
        aboutTitle.setText("About Us");
        aboutTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        aboutTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutTitleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(homeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidebarPanelLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(redWine)
                            .addGap(22, 22, 22))
                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(whiteWine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roseWine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wineTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(homeLogo)
                .addGap(24, 24, 24)
                .addComponent(wineTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roseWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(whiteWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        Background.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactTitleMouseClicked
        hideAllPanels();
        contactPanel.setVisible(true);
    }//GEN-LAST:event_contactTitleMouseClicked

    private void aboutTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTitleMouseClicked
        hideAllPanels();
        aboutPanel.setVisible(true);
    }//GEN-LAST:event_aboutTitleMouseClicked

    private void whiteWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiteWineMouseClicked
        hideAllPanels();
        whitePanel.setVisible(true);
    }//GEN-LAST:event_whiteWineMouseClicked

    private void roseWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roseWineMouseClicked
        hideAllPanels();
        rosePanel.setVisible(true);
    }//GEN-LAST:event_roseWineMouseClicked

    private void redWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redWineMouseClicked
        hideAllPanels();
        redPanel.setVisible(true);
    }//GEN-LAST:event_redWineMouseClicked

    private void wineTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wineTitleMouseClicked
        hideAllPanels();
        winePanel.setVisible(true);
    }//GEN-LAST:event_wineTitleMouseClicked

    private void homeLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLogoMouseClicked
        hideAllPanels();
        homePanel.setVisible(true);
    }//GEN-LAST:event_homeLogoMouseClicked

    private void heartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heartIconMouseClicked
        hideAllPanels();
        heartPanel.setVisible(true);
    }//GEN-LAST:event_heartIconMouseClicked

    private void cartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartIconMouseClicked
        hideAllPanels();
        cartPanel.setVisible(true);
    }//GEN-LAST:event_cartIconMouseClicked

    private void accountIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountIconMouseClicked
        hideAllPanels();
        accountPanel.setVisible(true);
    }//GEN-LAST:event_accountIconMouseClicked

    private void fullnameBaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameBaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameBaxActionPerformed

    private void emailBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailBoxActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton47ActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void surenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surenameActionPerformed

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void postalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalCodeActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel aboutBackground;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel aboutTitle;
    private javax.swing.JLabel aboutUsTitle;
    private javax.swing.JLabel accountIcon;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JTextField address;
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JPanel cartContainerPanel;
    private javax.swing.JLabel cartIcon;
    private javax.swing.JPanel cartInfoPanel;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JScrollPane cartScrollPane;
    private javax.swing.JTextField city;
    private javax.swing.JLabel contTitle;
    private javax.swing.JPanel contactContent;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JLabel contactTitle;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emailBox;
    private javax.swing.JLabel emailInfo;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailMsg;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel fullname;
    private javax.swing.JTextField fullnameBax;
    private javax.swing.JLabel fullnameMsg;
    private javax.swing.JLabel heartIcon;
    private javax.swing.JPanel heartPanel;
    private javax.swing.JLabel homeLogo;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homeTitle;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel infoTitle;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField messageBox;
    private javax.swing.JLabel msgTitle1;
    private javax.swing.JLabel msgTitle2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel ourPhotoAboutUs;
    private javax.swing.JPanel paddingPanel;
    private javax.swing.JPanel paddingPanel1;
    private javax.swing.JPanel paddingPanel2;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField postalCode;
    private javax.swing.JPanel pricesPanel;
    private javax.swing.JPanel productContainerPanel;
    private javax.swing.JLabel profileInfoTitle;
    private javax.swing.JLabel redBackground;
    private javax.swing.JPanel redBest;
    private javax.swing.JPanel redContainerPanel;
    private javax.swing.JPanel redPanel;
    private javax.swing.JScrollPane redScrollPane;
    private javax.swing.JLabel redTextLine1;
    private javax.swing.JLabel redTextLine2;
    private javax.swing.JLabel redTextLine3;
    private javax.swing.JLabel redTitle;
    private javax.swing.JLabel redWine;
    private javax.swing.JLabel redWineBackground;
    private javax.swing.JPanel redWinePanel;
    private javax.swing.JLabel roseBackground;
    private javax.swing.JPanel roseBest;
    private javax.swing.JPanel roseContainerPanel;
    private javax.swing.JPanel rosePanel;
    private javax.swing.JScrollPane roseScrollPane;
    private javax.swing.JLabel roseTextLine1;
    private javax.swing.JLabel roseTextLine2;
    private javax.swing.JLabel roseTextLine3;
    private javax.swing.JLabel roseTitle;
    private javax.swing.JLabel roseWine;
    private javax.swing.JLabel roseWineBackground;
    private javax.swing.JPanel roseWinePanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel shippingLb;
    private javax.swing.JLabel shippingPrice;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton submitCartBtn;
    private javax.swing.JLabel subtitleMsg;
    private javax.swing.JLabel subtotalLb;
    private javax.swing.JLabel subtotalPrice;
    private javax.swing.JTextField surename;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleWishlist;
    private javax.swing.JLabel topImage;
    private javax.swing.JLabel topImageProfile;
    private javax.swing.JPanel topbarPanel;
    private javax.swing.JLabel totalLb;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel username;
    private javax.swing.JLabel whiteBackground;
    private javax.swing.JPanel whiteBest;
    private javax.swing.JPanel whiteContainerPanel;
    private javax.swing.JPanel whitePanel;
    private javax.swing.JScrollPane whiteScrollPane;
    private javax.swing.JLabel whiteTextLine1;
    private javax.swing.JLabel whiteTextLine2;
    private javax.swing.JLabel whiteTextLine3;
    private javax.swing.JLabel whiteTitle;
    private javax.swing.JLabel whiteWine;
    private javax.swing.JLabel whiteWineBackground;
    private javax.swing.JPanel whiteWinePanel;
    private javax.swing.JLabel winePageBackground;
    private javax.swing.JLabel winePageTitle;
    private javax.swing.JPanel winePanel;
    private javax.swing.JLabel wineTitle;
    private javax.swing.JScrollPane wishlistScrollPane;
    // End of variables declaration//GEN-END:variables
}
