package winepackage;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setResizable(false);
        setTitle("Wine E-Shop");
        setIconImage(new ImageIcon(getClass().getResource("images/wine.png")).getImage());
        
        makeLabelClickable(wineTitle, 1, "Wine Title");
        makeLabelClickable(redWine, 2, "Red Wine");
        makeLabelClickable(roseWine, 3, "Rose Wine");
        makeLabelClickable(whiteWine, 4, "White Wine");
        makeLabelClickable(homeLogo, 5, "Home");
        makeLabelClickable(contactTitle, 6, "Contact");
        makeLabelClickable(aboutTitle, 7, "About");
        makeLabelClickable(accountIcon, 8, "Account");
        makeLabelClickable(cartIcon, 9, "Cart");
        makeLabelClickable(heartIcon, 10, "Favorites");
        
        hideAllPanels();
        homePanel.setVisible(true); // Show home by default
    }
    
    private void makeLabelClickable(JLabel label, int actionCode, String name) {
        label.setCursor(new Cursor(Cursor.HAND_CURSOR));
            //label.setForeground(new Color(115, 1, 18));
            label.setForeground(Color.WHITE);

        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println(name + " clicked! Action code: " + actionCode);

                // Future actions based on the action code
                switch (actionCode) {
                    case 1:
                        // action for wineTitle
                        System.out.println("Go to main wine page");
                        break;
                    case 2:
                        // red wine
                        System.out.println("Show red wine catalog");
                        break;
                    case 3:
                        // rose wine
                        System.out.println("Show rose wine catalog");
                        break;
                    case 4:
                        // white wine
                        System.out.println("Show white wine catalog");
                        break;
                    case 5:
                        System.out.println("Navigate to homepage");
                        break;
                    case 6:
                        System.out.println("Open contact section");
                        break;
                    case 7:
                        System.out.println("Open about section");
                        break;
                    case 8:
                        System.out.println("Open account/login screen");
                        break;
                    case 9:
                        System.out.println("Show cart");
                        break;
                    case 10:
                        System.out.println("Show favorites");
                        break;
                    default:
                        System.out.println("Unknown action");
                }
            }
        });
    }
    private void hideAllPanels() {
        homePanel.setVisible(false);
        winePanel.setVisible(false);
        redPanel.setVisible(false);
        rosePanel.setVisible(false);
        whitePanel.setVisible(false);
        contactPanel.setVisible(false);
        aboutPanel.setVisible(false);
        heartPanel.setVisible(false);
        cartPanel.setVisible(false);
        accountPanel.setVisible(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        sidebarPanel = new javax.swing.JPanel();
        homeLogo = new javax.swing.JLabel();
        wineTitle = new javax.swing.JLabel();
        redWine = new javax.swing.JLabel();
        roseWine = new javax.swing.JLabel();
        whiteWine = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        contactTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        aboutTitle = new javax.swing.JLabel();
        topbarPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        accountIcon = new javax.swing.JLabel();
        cartIcon = new javax.swing.JLabel();
        heartIcon = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        homePanel = new javax.swing.JPanel();
        winePanel = new javax.swing.JPanel();
        redPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        rosePanel = new javax.swing.JPanel();
        whitePanel = new javax.swing.JPanel();
        contactPanel = new javax.swing.JPanel();
        aboutPanel = new javax.swing.JPanel();
        heartPanel = new javax.swing.JPanel();
        cartPanel = new javax.swing.JPanel();
        accountPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(115, 1, 18));
        Background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 1170, 10));

        jSeparator5.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, -1, 10, 650));

        sidebarPanel.setBackground(new java.awt.Color(179, 110, 120));

        homeLogo.setBackground(new java.awt.Color(179, 110, 120));
        homeLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/home (3).png"))); // NOI18N
        homeLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLogoMouseClicked(evt);
            }
        });

        wineTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        wineTitle.setForeground(new java.awt.Color(255, 255, 255));
        wineTitle.setText("Wines");
        wineTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wineTitleMouseClicked(evt);
            }
        });

        redWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        redWine.setForeground(new java.awt.Color(255, 255, 255));
        redWine.setText("▸Red");
        redWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redWineMouseClicked(evt);
            }
        });

        roseWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        roseWine.setForeground(new java.awt.Color(255, 255, 255));
        roseWine.setText("▸Rose");
        roseWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roseWineMouseClicked(evt);
            }
        });

        whiteWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        whiteWine.setForeground(new java.awt.Color(255, 255, 255));
        whiteWine.setText("▸White");
        whiteWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteWineMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(115, 1, 18));

        contactTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        contactTitle.setForeground(new java.awt.Color(255, 255, 255));
        contactTitle.setText("Contact");
        contactTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contactTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactTitleMouseClicked(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(115, 1, 18));

        aboutTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        aboutTitle.setForeground(new java.awt.Color(255, 255, 255));
        aboutTitle.setText("About Us");
        aboutTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        aboutTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutTitleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(homeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidebarPanelLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(redWine)
                            .addGap(22, 22, 22))
                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(whiteWine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roseWine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wineTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(homeLogo)
                .addGap(24, 24, 24)
                .addComponent(wineTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roseWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(whiteWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        Background.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 660));

        topbarPanel.setBackground(new java.awt.Color(179, 110, 120));

        jSeparator2.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        accountIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/account.png"))); // NOI18N
        accountIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountIconMouseClicked(evt);
            }
        });

        cartIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/grocery-store.png"))); // NOI18N
        cartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartIconMouseClicked(evt);
            }
        });

        heartIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/heart.png"))); // NOI18N
        heartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heartIconMouseClicked(evt);
            }
        });

        searchField.setBackground(new java.awt.Color(254, 199, 207));
        searchField.setText("Search for the wines you want...");

        searchButton.setBackground(new java.awt.Color(252, 129, 147));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchButton.setText("Search");

        jSeparator6.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout topbarPanelLayout = new javax.swing.GroupLayout(topbarPanel);
        topbarPanel.setLayout(topbarPanelLayout);
        topbarPanelLayout.setHorizontalGroup(
            topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topbarPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addGap(118, 118, 118)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(heartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        topbarPanelLayout.setVerticalGroup(
            topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topbarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addComponent(cartIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(topbarPanelLayout.createSequentialGroup()
                .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(topbarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heartIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topbarPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(accountIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Background.add(topbarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1030, 70));

        homePanel.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        winePanel.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout winePanelLayout = new javax.swing.GroupLayout(winePanel);
        winePanel.setLayout(winePanelLayout);
        winePanelLayout.setHorizontalGroup(
            winePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        winePanelLayout.setVerticalGroup(
            winePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(winePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        redPanel.setBackground(new java.awt.Color(204, 0, 0));
        redPanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel1);
        jPanel1.setBounds(810, 30, 170, 170);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel2);
        jPanel2.setBounds(280, 40, 170, 170);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel3);
        jPanel3.setBounds(810, 300, 170, 170);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel4);
        jPanel4.setBounds(590, 30, 170, 170);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel5);
        jPanel5.setBounds(50, 40, 170, 170);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel6);
        jPanel6.setBounds(50, 300, 170, 170);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel7);
        jPanel7.setBounds(280, 300, 170, 170);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel9);
        jPanel9.setBounds(590, 300, 170, 170);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/advertisement-wine-with-floating-bottle.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        redPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 580);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        redPanel.add(jPanel8);
        jPanel8.setBounds(590, 300, 170, 170);

        Background.add(redPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        rosePanel.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout rosePanelLayout = new javax.swing.GroupLayout(rosePanel);
        rosePanel.setLayout(rosePanelLayout);
        rosePanelLayout.setHorizontalGroup(
            rosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        rosePanelLayout.setVerticalGroup(
            rosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(rosePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        whitePanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout whitePanelLayout = new javax.swing.GroupLayout(whitePanel);
        whitePanel.setLayout(whitePanelLayout);
        whitePanelLayout.setHorizontalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        whitePanelLayout.setVerticalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(whitePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        contactPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout contactPanelLayout = new javax.swing.GroupLayout(contactPanel);
        contactPanel.setLayout(contactPanelLayout);
        contactPanelLayout.setHorizontalGroup(
            contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        contactPanelLayout.setVerticalGroup(
            contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(contactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        aboutPanel.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        heartPanel.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout heartPanelLayout = new javax.swing.GroupLayout(heartPanel);
        heartPanel.setLayout(heartPanelLayout);
        heartPanelLayout.setHorizontalGroup(
            heartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        heartPanelLayout.setVerticalGroup(
            heartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(heartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        cartPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
        cartPanel.setLayout(cartPanelLayout);
        cartPanelLayout.setHorizontalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        cartPanelLayout.setVerticalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(cartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        accountPanel.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(accountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactTitleMouseClicked
        hideAllPanels();
        contactPanel.setVisible(true);
    }//GEN-LAST:event_contactTitleMouseClicked

    private void aboutTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTitleMouseClicked
        hideAllPanels();
        aboutPanel.setVisible(true);
    }//GEN-LAST:event_aboutTitleMouseClicked

    private void whiteWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiteWineMouseClicked
        hideAllPanels();
        whitePanel.setVisible(true);
    }//GEN-LAST:event_whiteWineMouseClicked

    private void roseWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roseWineMouseClicked
        hideAllPanels();
        rosePanel.setVisible(true);
    }//GEN-LAST:event_roseWineMouseClicked

    private void redWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redWineMouseClicked
        hideAllPanels();
        redPanel.setVisible(true);
    }//GEN-LAST:event_redWineMouseClicked

    private void wineTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wineTitleMouseClicked
        hideAllPanels();
        winePanel.setVisible(true);
    }//GEN-LAST:event_wineTitleMouseClicked

    private void homeLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLogoMouseClicked
        hideAllPanels();
        homePanel.setVisible(true);
    }//GEN-LAST:event_homeLogoMouseClicked

    private void heartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heartIconMouseClicked
        hideAllPanels();
        heartPanel.setVisible(true);
    }//GEN-LAST:event_heartIconMouseClicked

    private void cartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartIconMouseClicked
        hideAllPanels();
        cartPanel.setVisible(true);
    }//GEN-LAST:event_cartIconMouseClicked

    private void accountIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountIconMouseClicked
        hideAllPanels();
        accountPanel.setVisible(true);
    }//GEN-LAST:event_accountIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel aboutTitle;
    private javax.swing.JLabel accountIcon;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JLabel cartIcon;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JLabel contactTitle;
    private javax.swing.JLabel heartIcon;
    private javax.swing.JPanel heartPanel;
    private javax.swing.JLabel homeLogo;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel redPanel;
    private javax.swing.JLabel redWine;
    private javax.swing.JPanel rosePanel;
    private javax.swing.JLabel roseWine;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel topbarPanel;
    private javax.swing.JPanel whitePanel;
    private javax.swing.JLabel whiteWine;
    private javax.swing.JPanel winePanel;
    private javax.swing.JLabel wineTitle;
    // End of variables declaration//GEN-END:variables
}
