package winepackage;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setResizable(false);
        setTitle("Wine E-Shop");
        setIconImage(new ImageIcon(getClass().getResource("images/wine.png")).getImage());
        
        makeLabelClickable(wineTitle, 1, "Wine Title");
        makeLabelClickable(redWine, 2, "Red Wine");
        makeLabelClickable(roseWine, 3, "Rose Wine");
        makeLabelClickable(whiteWine, 4, "White Wine");
        makeLabelClickable(homeLogo, 5, "Home");
        makeLabelClickable(contactTitle, 6, "Contact");
        makeLabelClickable(aboutTitle, 7, "About");
        makeLabelClickable(accountIcon, 8, "Account");
        makeLabelClickable(cartIcon, 9, "Cart");
        makeLabelClickable(heartIcon, 10, "Favorites");
        
        hideAllPanels();
        homePanel.setVisible(true); // Show home by default
    }
    
    private void makeLabelClickable(JLabel label, int actionCode, String name) {
        label.setCursor(new Cursor(Cursor.HAND_CURSOR));
            //label.setForeground(new Color(115, 1, 18));
            label.setForeground(Color.WHITE);

        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println(name + " clicked! Action code: " + actionCode);

                // Future actions based on the action code
                switch (actionCode) {
                    case 1:
                        // action for wineTitle
                        System.out.println("Go to main wine page");
                        break;
                    case 2:
                        // red wine
                        System.out.println("Show red wine catalog");
                        break;
                    case 3:
                        // rose wine
                        System.out.println("Show rose wine catalog");
                        break;
                    case 4:
                        // white wine
                        System.out.println("Show white wine catalog");
                        break;
                    case 5:
                        System.out.println("Navigate to homepage");
                        break;
                    case 6:
                        System.out.println("Open contact section");
                        break;
                    case 7:
                        System.out.println("Open about section");
                        break;
                    case 8:
                        System.out.println("Open account/login screen");
                        break;
                    case 9:
                        System.out.println("Show cart");
                        break;
                    case 10:
                        System.out.println("Show favorites");
                        break;
                    default:
                        System.out.println("Unknown action");
                }
            }
        });
    }
    private void hideAllPanels() {
        homePanel.setVisible(false);
        winePanel.setVisible(false);
        redPanel.setVisible(false);
        rosePanel.setVisible(false);
        whitePanel.setVisible(false);
        contactPanel.setVisible(false);
        aboutPanel.setVisible(false);
        heartPanel.setVisible(false);
        cartPanel.setVisible(false);
        accountPanel.setVisible(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jLabel135 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        jPanel73 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jLabel139 = new javax.swing.JLabel();
        jPanel74 = new javax.swing.JPanel();
        jPanel75 = new javax.swing.JPanel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jLabel143 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contactPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel157 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel126 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        jLabel161 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        heartPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productContainerPanel = new javax.swing.JPanel();
        cartPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        accountPanel = new javax.swing.JPanel();
        jLabel159 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        winePanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        redPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paddingPanel = new javax.swing.JPanel();
        redContainerPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rosePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        paddingPanel1 = new javax.swing.JPanel();
        roseContainerPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        whitePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        paddingPanel2 = new javax.swing.JPanel();
        whiteContainerPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        topbarPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        accountIcon = new javax.swing.JLabel();
        cartIcon = new javax.swing.JLabel();
        heartIcon = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        sidebarPanel = new javax.swing.JPanel();
        homeLogo = new javax.swing.JLabel();
        wineTitle = new javax.swing.JLabel();
        redWine = new javax.swing.JLabel();
        roseWine = new javax.swing.JLabel();
        whiteWine = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        contactTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        aboutTitle = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1166, 0));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setBackground(new java.awt.Color(153, 153, 255));
        homePanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Serif", 3, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Our Best Sellers");
        homePanel.add(jLabel3);
        jLabel3.setBounds(340, 300, 350, 40);

        jPanel68.setBackground(new java.awt.Color(255, 255, 255));

        jPanel71.setBackground(new java.awt.Color(255, 255, 255));

        jLabel128.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel128.setText("Zero Sauvignon Blanc");

        jLabel129.setForeground(new java.awt.Color(51, 51, 51));
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel129.setText("Ξηρός, Ήπιος, Λευκός");

        jLabel130.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel130.setText("10,60 €");

        jButton31.setBackground(new java.awt.Color(179, 110, 120));
        jButton31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton31.setText("Buy");

        jButton46.setBackground(new java.awt.Color(179, 110, 120));
        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton46.setText("♡");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel128, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel71Layout.createSequentialGroup()
                        .addComponent(jLabel130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel128)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel129)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel130)
                    .addComponent(jButton31)
                    .addComponent(jButton46))
                .addContainerGap())
        );

        jLabel135.setBackground(new java.awt.Color(255, 255, 255));
        jLabel135.setForeground(new java.awt.Color(255, 255, 255));
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image-from-rawpixel-id-6469258-png (1).png"))); // NOI18N
        jLabel135.setText(" ");

        javax.swing.GroupLayout jPanel68Layout = new javax.swing.GroupLayout(jPanel68);
        jPanel68.setLayout(jPanel68Layout);
        jPanel68Layout.setHorizontalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel71, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel68Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel135, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel68Layout.setVerticalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel68Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel135, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePanel.add(jPanel68);
        jPanel68.setBounds(430, 350, 170, 210);

        jPanel72.setBackground(new java.awt.Color(255, 255, 255));

        jPanel73.setBackground(new java.awt.Color(255, 255, 255));

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel136.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel136.setText("Zero Sauvignon Blanc");

        jLabel137.setForeground(new java.awt.Color(51, 51, 51));
        jLabel137.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel137.setText("Ξηρός, Ήπιος, Λευκός");

        jLabel138.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel138.setText("10,60 €");

        jButton33.setBackground(new java.awt.Color(179, 110, 120));
        jButton33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton33.setText("Buy");

        jButton35.setBackground(new java.awt.Color(179, 110, 120));
        jButton35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton35.setText("♡");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel73Layout = new javax.swing.GroupLayout(jPanel73);
        jPanel73.setLayout(jPanel73Layout);
        jPanel73Layout.setHorizontalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel136, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel137, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel73Layout.createSequentialGroup()
                        .addComponent(jLabel138)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel73Layout.setVerticalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel136)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel137)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel138)
                    .addComponent(jButton33)
                    .addComponent(jButton35))
                .addContainerGap())
        );

        jLabel139.setBackground(new java.awt.Color(255, 255, 255));
        jLabel139.setForeground(new java.awt.Color(255, 255, 255));
        jLabel139.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel139.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image-from-rawpixel-id-6469258-png (1).png"))); // NOI18N
        jLabel139.setText(" ");

        javax.swing.GroupLayout jPanel72Layout = new javax.swing.GroupLayout(jPanel72);
        jPanel72.setLayout(jPanel72Layout);
        jPanel72Layout.setHorizontalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel73, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel72Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel72Layout.setVerticalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel72Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel139, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePanel.add(jPanel72);
        jPanel72.setBounds(110, 350, 170, 210);

        jPanel74.setBackground(new java.awt.Color(255, 255, 255));

        jPanel75.setBackground(new java.awt.Color(255, 255, 255));

        jLabel140.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel140.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel140.setText("Zero Sauvignon Blanc");

        jLabel141.setForeground(new java.awt.Color(51, 51, 51));
        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel141.setText("Ξηρός, Ήπιος, Λευκός");

        jLabel142.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel142.setText("10,60 €");

        jButton34.setBackground(new java.awt.Color(179, 110, 120));
        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton34.setText("Buy");

        jButton47.setBackground(new java.awt.Color(179, 110, 120));
        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton47.setText("♡");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel75Layout = new javax.swing.GroupLayout(jPanel75);
        jPanel75.setLayout(jPanel75Layout);
        jPanel75Layout.setHorizontalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel75Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel140, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel141, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel75Layout.createSequentialGroup()
                        .addComponent(jLabel142)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel75Layout.setVerticalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel140)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel141)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel142)
                    .addComponent(jButton34)
                    .addComponent(jButton47))
                .addContainerGap())
        );

        jLabel143.setBackground(new java.awt.Color(255, 255, 255));
        jLabel143.setForeground(new java.awt.Color(255, 255, 255));
        jLabel143.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image-from-rawpixel-id-6469258-png (1).png"))); // NOI18N
        jLabel143.setText(" ");

        javax.swing.GroupLayout jPanel74Layout = new javax.swing.GroupLayout(jPanel74);
        jPanel74.setLayout(jPanel74Layout);
        jPanel74Layout.setHorizontalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel75, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel74Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel143, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel74Layout.setVerticalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel74Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePanel.add(jPanel74);
        jPanel74.setBounds(750, 350, 170, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/WINE_NOT__20250521_223250_0000.png"))); // NOI18N
        jLabel2.setText(" ");
        homePanel.add(jLabel2);
        jLabel2.setBounds(0, 0, 1030, 580);

        Background.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        contactPanel.setBackground(new java.awt.Color(0, 153, 153));
        contactPanel.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(171, 1, 26));

        jLabel127.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(255, 255, 255));
        jLabel127.setText("Let's Start a Convertation");

        jLabel154.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        jLabel154.setForeground(new java.awt.Color(255, 255, 255));
        jLabel154.setText("Please note: all fields are required.");

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel155.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        jLabel155.setForeground(new java.awt.Color(255, 255, 255));
        jLabel155.setText("Fullname:");

        jLabel156.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(255, 255, 255));
        jLabel156.setText("Email:");

        jTextField2.setText("  ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel157.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(255, 255, 255));
        jLabel157.setText("Write the reason for contacting:");

        jTextField3.setText("  ");

        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(235, 4, 36));
        jButton1.setText("Submit");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel154)
                    .addComponent(jLabel127))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel156)
                    .addComponent(jLabel155))
                .addGap(85, 85, 85)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel157))
                .addGap(172, 172, 172))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel127)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel154)
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel155, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel157))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel156)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        contactPanel.add(jPanel11);
        jPanel11.setBounds(0, 290, 1030, 290);

        jLabel126.setFont(new java.awt.Font("Noto Serif", 1, 48)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(255, 255, 255));
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setText("Contact Us");
        contactPanel.add(jLabel126);
        jLabel126.setBounds(340, 190, 340, 110);

        jLabel125.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/pexels-adrian-odogwu-2078202-3820514(1)(1).jpg"))); // NOI18N
        jLabel125.setText(" ");
        contactPanel.add(jLabel125);
        jLabel125.setBounds(0, 0, 1030, 290);

        Background.add(contactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        aboutPanel.setBackground(new java.awt.Color(171, 1, 26));
        aboutPanel.setLayout(null);

        jLabel161.setFont(new java.awt.Font("Noto Serif", 1, 48)); // NOI18N
        jLabel161.setForeground(new java.awt.Color(255, 255, 255));
        jLabel161.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel161.setText("About Us");
        aboutPanel.add(jLabel161);
        jLabel161.setBounds(340, 150, 340, 110);

        jLabel160.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/freepik__make-the-background-abstract-with-soft-pastel-colo__79196.png"))); // NOI18N
        jLabel160.setText(" ");
        aboutPanel.add(jLabel160);
        jLabel160.setBounds(280, 230, 450, 240);

        jLabel158.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/pexels-adrian-odogwu-2078202-3820514(1)(1).jpg"))); // NOI18N
        jLabel158.setText(" ");
        jLabel158.setPreferredSize(new java.awt.Dimension(1030, 290));
        aboutPanel.add(jLabel158);
        jLabel158.setBounds(0, 0, 1038, 290);

        Background.add(aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        heartPanel.setBackground(new java.awt.Color(171, 1, 26));

        jLabel9.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Wishlist");

        for (int i = 0; i < 30; i++) {
            ProductBoxPanel box = new ProductBoxPanel();

            productContainerPanel.add(box);
        }
        productContainerPanel.revalidate();
        productContainerPanel.repaint();
        productContainerPanel.setLayout(new javax.swing.BoxLayout(productContainerPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane3.setViewportView(productContainerPanel);

        javax.swing.GroupLayout heartPanelLayout = new javax.swing.GroupLayout(heartPanel);
        heartPanel.setLayout(heartPanelLayout);
        heartPanelLayout.setHorizontalGroup(
            heartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heartPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(heartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        heartPanelLayout.setVerticalGroup(
            heartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heartPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Background.add(heartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        cartPanel.setBackground(new java.awt.Color(204, 255, 204));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
        cartPanel.setLayout(cartPanelLayout);
        cartPanelLayout.setHorizontalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        cartPanelLayout.setVerticalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 248, Short.MAX_VALUE))
        );

        Background.add(cartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        accountPanel.setBackground(new java.awt.Color(40, 0, 6));
        accountPanel.setLayout(null);

        jLabel159.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel159.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/user(1).png"))); // NOI18N
        jLabel159.setText("  ");
        accountPanel.add(jLabel159);
        jLabel159.setBounds(110, 130, 110, 102);

        jLabel162.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        jLabel162.setForeground(new java.awt.Color(255, 255, 255));
        jLabel162.setText("Username");
        accountPanel.add(jLabel162);
        jLabel162.setBounds(220, 160, 270, 50);

        jLabel164.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel164.setText("Τηλέφωνο:");

        jLabel165.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel165.setText("Ονοματεπώνυμο:");

        jLabel166.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel166.setText("Email:");

        jLabel167.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        jLabel167.setText("Όναμα Επώνημο");

        jLabel168.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        jLabel168.setText("exampleemail@email.com");

        jLabel169.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        jLabel169.setText("6901234567");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel165, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel166, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel168)
                            .addComponent(jLabel167)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel164, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel169)))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel165, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel167))
                .addGap(42, 42, 42)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel166, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel168))
                .addGap(42, 42, 42)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel164, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel169))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        accountPanel.add(jPanel12);
        jPanel12.setBounds(110, 260, 810, 290);

        jLabel163.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        jLabel163.setForeground(new java.awt.Color(255, 255, 255));
        jLabel163.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel163.setText("Your Info");
        accountPanel.add(jLabel163);
        jLabel163.setBounds(440, 220, 130, 40);

        jLabel170.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/pexels-adrian-odogwu-2078202-3820514(1)(1).jpg"))); // NOI18N
        jLabel170.setText("  ");
        accountPanel.add(jLabel170);
        jLabel170.setBounds(0, 0, 1030, 290);

        Background.add(accountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        winePanel.setBackground(new java.awt.Color(0, 204, 51));
        winePanel.setLayout(null);

        jPanel5.setLayout(null);

        jLabel147.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel147.setForeground(new java.awt.Color(204, 0, 0));
        jLabel147.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel147.setText("red wines");
        jLabel147.setToolTipText("");
        jLabel147.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel147.setName(""); // NOI18N
        jPanel5.add(jLabel147);
        jLabel147.setBounds(0, 70, 200, 70);

        jLabel148.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(204, 0, 0));
        jLabel148.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel148.setText("Check our ");
        jLabel148.setToolTipText("");
        jLabel148.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel148.setName(""); // NOI18N
        jPanel5.add(jLabel148);
        jLabel148.setBounds(0, -10, 200, 70);

        jLabel149.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel149.setForeground(new java.awt.Color(204, 0, 0));
        jLabel149.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel149.setText("list of");
        jLabel149.setToolTipText("");
        jLabel149.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel149.setName(""); // NOI18N
        jPanel5.add(jLabel149);
        jLabel149.setBounds(0, 30, 200, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image (2).png"))); // NOI18N
        jLabel7.setText(" ");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(0, 0, 208, 210);

        winePanel.add(jPanel5);
        jPanel5.setBounds(420, 300, 200, 210);

        jPanel8.setLayout(null);

        jLabel144.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(255, 255, 255));
        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel144.setText("white wines");
        jLabel144.setToolTipText("");
        jLabel144.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel144.setName(""); // NOI18N
        jPanel8.add(jLabel144);
        jLabel144.setBounds(0, 70, 200, 70);

        jLabel145.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(255, 255, 255));
        jLabel145.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel145.setText("Check our ");
        jLabel145.setToolTipText("");
        jLabel145.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel145.setName(""); // NOI18N
        jPanel8.add(jLabel145);
        jLabel145.setBounds(0, -10, 200, 70);

        jLabel146.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(255, 255, 255));
        jLabel146.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel146.setText("list of");
        jLabel146.setToolTipText("");
        jLabel146.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel146.setName(""); // NOI18N
        jPanel8.add(jLabel146);
        jLabel146.setBounds(0, 30, 200, 70);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image (2).png"))); // NOI18N
        jLabel6.setText(" ");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(0, 0, 208, 210);

        winePanel.add(jPanel8);
        jPanel8.setBounds(80, 300, 200, 210);

        jPanel10.setLayout(null);

        jLabel150.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel150.setForeground(new java.awt.Color(255, 153, 153));
        jLabel150.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel150.setText("list of");
        jLabel150.setToolTipText("");
        jLabel150.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel150.setName(""); // NOI18N
        jPanel10.add(jLabel150);
        jLabel150.setBounds(0, 30, 200, 70);

        jLabel151.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(255, 153, 153));
        jLabel151.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel151.setText("Check our ");
        jLabel151.setToolTipText("");
        jLabel151.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel151.setName(""); // NOI18N
        jPanel10.add(jLabel151);
        jLabel151.setBounds(0, -10, 200, 70);

        jLabel152.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel152.setForeground(new java.awt.Color(255, 153, 153));
        jLabel152.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel152.setText("rose wines");
        jLabel152.setToolTipText("");
        jLabel152.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel152.setName(""); // NOI18N
        jPanel10.add(jLabel152);
        jLabel152.setBounds(0, 70, 200, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/image (2).png"))); // NOI18N
        jLabel8.setText(" ");
        jPanel10.add(jLabel8);
        jLabel8.setBounds(0, 0, 208, 210);

        winePanel.add(jPanel10);
        jPanel10.setBounds(760, 300, 200, 210);

        jLabel5.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Our Wines");
        winePanel.add(jLabel5);
        jLabel5.setBounds(380, 50, 290, 40);

        jLabel153.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/WINE_NOT__20250521_223250_0000.png"))); // NOI18N
        jLabel153.setText(" ");
        winePanel.add(jLabel153);
        jLabel153.setBounds(0, 0, 1030, 580);

        Background.add(winePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        redPanel.setBackground(new java.awt.Color(171, 1, 26));
        redPanel.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Red Wines");
        redPanel.add(jLabel10);
        jLabel10.setBounds(400, 10, 250, 50);

        jScrollPane1.setBackground(new java.awt.Color(179, 110, 120));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        paddingPanel.setBackground(new java.awt.Color(179, 110, 120));
        paddingPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 0, 0));
        paddingPanel.setLayout(new java.awt.BorderLayout());

        redContainerPanel.setBackground(new java.awt.Color(179, 110, 120));
        redContainerPanel.setAutoscrolls(true);
        redContainerPanel.setMaximumSize(new java.awt.Dimension(180, 180));
        redContainerPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

        for (int i = 0; i < 20; i++) {
            ProductSquerePanel box = new ProductSquerePanel();
            redContainerPanel.add(box); // This is your JPanel inside JScrollPane
        }
        redContainerPanel.revalidate();
        redContainerPanel.repaint();
        redContainerPanel.setLayout(new java.awt.GridLayout(0, 4));
        paddingPanel.add(redContainerPanel, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(paddingPanel);

        redPanel.add(jScrollPane1);
        jScrollPane1.setBounds(40, 60, 940, 510);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/advertisement-wine-with-floating-bottle.jpg"))); // NOI18N
        jLabel11.setToolTipText("");
        redPanel.add(jLabel11);
        jLabel11.setBounds(0, 0, 1030, 580);

        Background.add(redPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        rosePanel.setBackground(new java.awt.Color(171, 1, 26));
        rosePanel.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Rose Wines");
        rosePanel.add(jLabel12);
        jLabel12.setBounds(0, 10, 1030, 50);

        jScrollPane4.setBackground(new java.awt.Color(179, 110, 120));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        paddingPanel1.setBackground(new java.awt.Color(179, 110, 120));
        paddingPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 0, 0));
        paddingPanel1.setLayout(new java.awt.BorderLayout());

        roseContainerPanel.setBackground(new java.awt.Color(179, 110, 120));
        roseContainerPanel.setAutoscrolls(true);
        roseContainerPanel.setMaximumSize(new java.awt.Dimension(180, 180));
        roseContainerPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

        for (int i = 0; i < 20; i++) {
            ProductSquerePanel box = new ProductSquerePanel();
            roseContainerPanel.add(box); // This is your JPanel inside JScrollPane
        }
        roseContainerPanel.revalidate();
        roseContainerPanel.repaint();
        roseContainerPanel.setLayout(new java.awt.GridLayout(0, 4));
        paddingPanel1.add(roseContainerPanel, java.awt.BorderLayout.CENTER);

        jScrollPane4.setViewportView(paddingPanel1);

        rosePanel.add(jScrollPane4);
        jScrollPane4.setBounds(40, 60, 940, 510);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/freepik__make-the-background-abstract-with-soft-pastel-colo__79196.png"))); // NOI18N
        jLabel13.setToolTipText("");
        rosePanel.add(jLabel13);
        jLabel13.setBounds(0, 0, 1030, 580);

        Background.add(rosePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        whitePanel.setBackground(new java.awt.Color(171, 1, 26));
        whitePanel.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("White Wines");
        whitePanel.add(jLabel14);
        jLabel14.setBounds(0, 10, 1030, 50);

        jScrollPane5.setBackground(new java.awt.Color(179, 110, 120));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        paddingPanel2.setBackground(new java.awt.Color(179, 110, 120));
        paddingPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 0, 0));
        paddingPanel2.setLayout(new java.awt.BorderLayout());

        whiteContainerPanel.setBackground(new java.awt.Color(179, 110, 120));
        whiteContainerPanel.setAutoscrolls(true);
        whiteContainerPanel.setMaximumSize(new java.awt.Dimension(180, 180));
        whiteContainerPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

        for (int i = 0; i < 20; i++) {
            ProductSquerePanel box = new ProductSquerePanel();
            whiteContainerPanel.add(box); // This is your JPanel inside JScrollPane
        }
        whiteContainerPanel.revalidate();
        whiteContainerPanel.repaint();
        whiteContainerPanel.setLayout(new java.awt.GridLayout(0, 4));
        paddingPanel2.add(whiteContainerPanel, java.awt.BorderLayout.CENTER);

        jScrollPane5.setViewportView(paddingPanel2);

        whitePanel.add(jScrollPane5);
        jScrollPane5.setBounds(40, 60, 940, 510);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/freepik__transform-the-red-wine-bottle-into-a-white-wine-bo__79195.png"))); // NOI18N
        jLabel15.setToolTipText("");
        whitePanel.add(jLabel15);
        jLabel15.setBounds(0, 0, 1030, 580);

        Background.add(whitePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1030, 580));

        topbarPanel.setBackground(new java.awt.Color(179, 110, 120));

        jSeparator2.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        accountIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/account.png"))); // NOI18N
        accountIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountIconMouseClicked(evt);
            }
        });

        cartIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/grocery-store.png"))); // NOI18N
        cartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartIconMouseClicked(evt);
            }
        });

        heartIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/heart.png"))); // NOI18N
        heartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heartIconMouseClicked(evt);
            }
        });

        searchField.setBackground(new java.awt.Color(254, 199, 207));
        searchField.setForeground(new java.awt.Color(255, 255, 255));
        searchField.setText("Search for the wines you want...");

        searchButton.setBackground(new java.awt.Color(252, 129, 147));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");

        jSeparator6.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout topbarPanelLayout = new javax.swing.GroupLayout(topbarPanel);
        topbarPanel.setLayout(topbarPanelLayout);
        topbarPanelLayout.setHorizontalGroup(
            topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topbarPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addGap(118, 118, 118)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(heartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        topbarPanelLayout.setVerticalGroup(
            topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topbarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addComponent(cartIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(topbarPanelLayout.createSequentialGroup()
                .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(topbarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heartIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topbarPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(topbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(accountIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Background.add(topbarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1030, 70));

        sidebarPanel.setBackground(new java.awt.Color(179, 110, 120));

        homeLogo.setBackground(new java.awt.Color(179, 110, 120));
        homeLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/home (3).png"))); // NOI18N
        homeLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLogoMouseClicked(evt);
            }
        });

        wineTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        wineTitle.setForeground(new java.awt.Color(255, 255, 255));
        wineTitle.setText("Wines");
        wineTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wineTitleMouseClicked(evt);
            }
        });

        redWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        redWine.setForeground(new java.awt.Color(255, 255, 255));
        redWine.setText("▸Red");
        redWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redWineMouseClicked(evt);
            }
        });

        roseWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        roseWine.setForeground(new java.awt.Color(255, 255, 255));
        roseWine.setText("▸Rose");
        roseWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roseWineMouseClicked(evt);
            }
        });

        whiteWine.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        whiteWine.setForeground(new java.awt.Color(255, 255, 255));
        whiteWine.setText("▸White");
        whiteWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteWineMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(115, 1, 18));

        contactTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        contactTitle.setForeground(new java.awt.Color(255, 255, 255));
        contactTitle.setText("Contact");
        contactTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contactTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactTitleMouseClicked(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(115, 1, 18));

        aboutTitle.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        aboutTitle.setForeground(new java.awt.Color(255, 255, 255));
        aboutTitle.setText("About Us");
        aboutTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        aboutTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutTitleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(homeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidebarPanelLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(redWine)
                            .addGap(22, 22, 22))
                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(whiteWine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roseWine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wineTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(homeLogo)
                .addGap(24, 24, 24)
                .addComponent(wineTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roseWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(whiteWine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        Background.add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 660));

        jSeparator5.setForeground(new java.awt.Color(115, 1, 18));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, -1, 10, 650));

        jSeparator4.setForeground(new java.awt.Color(115, 1, 18));
        Background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 1170, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactTitleMouseClicked
        hideAllPanels();
        contactPanel.setVisible(true);
    }//GEN-LAST:event_contactTitleMouseClicked

    private void aboutTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTitleMouseClicked
        hideAllPanels();
        aboutPanel.setVisible(true);
    }//GEN-LAST:event_aboutTitleMouseClicked

    private void whiteWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiteWineMouseClicked
        hideAllPanels();
        whitePanel.setVisible(true);
    }//GEN-LAST:event_whiteWineMouseClicked

    private void roseWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roseWineMouseClicked
        hideAllPanels();
        rosePanel.setVisible(true);
    }//GEN-LAST:event_roseWineMouseClicked

    private void redWineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redWineMouseClicked
        hideAllPanels();
        redPanel.setVisible(true);
    }//GEN-LAST:event_redWineMouseClicked

    private void wineTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wineTitleMouseClicked
        hideAllPanels();
        winePanel.setVisible(true);
    }//GEN-LAST:event_wineTitleMouseClicked

    private void homeLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLogoMouseClicked
        hideAllPanels();
        homePanel.setVisible(true);
    }//GEN-LAST:event_homeLogoMouseClicked

    private void heartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heartIconMouseClicked
        hideAllPanels();
        heartPanel.setVisible(true);
    }//GEN-LAST:event_heartIconMouseClicked

    private void cartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartIconMouseClicked
        hideAllPanels();
        cartPanel.setVisible(true);
    }//GEN-LAST:event_cartIconMouseClicked

    private void accountIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountIconMouseClicked
        hideAllPanels();
        accountPanel.setVisible(true);
    }//GEN-LAST:event_accountIconMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton47ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel aboutTitle;
    private javax.swing.JLabel accountIcon;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JLabel cartIcon;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JLabel contactTitle;
    private javax.swing.JLabel heartIcon;
    private javax.swing.JPanel heartPanel;
    private javax.swing.JLabel homeLogo;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel paddingPanel;
    private javax.swing.JPanel paddingPanel1;
    private javax.swing.JPanel paddingPanel2;
    private javax.swing.JPanel productContainerPanel;
    private javax.swing.JPanel redContainerPanel;
    private javax.swing.JPanel redPanel;
    private javax.swing.JLabel redWine;
    private javax.swing.JPanel roseContainerPanel;
    private javax.swing.JPanel rosePanel;
    private javax.swing.JLabel roseWine;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel topbarPanel;
    private javax.swing.JPanel whiteContainerPanel;
    private javax.swing.JPanel whitePanel;
    private javax.swing.JLabel whiteWine;
    private javax.swing.JPanel winePanel;
    private javax.swing.JLabel wineTitle;
    // End of variables declaration//GEN-END:variables
}
