/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package winepackage;

/**
 *
 * @author dimit
 */
public class ProductBoxPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductBoxPanel
     */
    public ProductBoxPanel() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productBoxPanel = new javax.swing.JPanel();
        productBoxCont = new javax.swing.JPanel();
        productTitle = new javax.swing.JLabel();
        productInfo = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        productLikeBtn = new javax.swing.JButton();
        productPhoto = new javax.swing.JLabel();
        productBuyBtn = new javax.swing.JButton();

        productBoxPanel.setBackground(new java.awt.Color(255, 255, 255));
        productBoxPanel.setLayout(new javax.swing.BoxLayout(productBoxPanel, javax.swing.BoxLayout.X_AXIS));

        productBoxCont.setBackground(new java.awt.Color(255, 255, 255));

        productTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        productTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productTitle.setText("Zero Sauvignon Blanc");

        productInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productInfo.setForeground(new java.awt.Color(51, 51, 51));
        productInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productInfo.setText("Ξηρός, Ήπιος, Λευκός");

        productPrice.setBackground(new java.awt.Color(0, 0, 0));
        productPrice.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        productPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productPrice.setText("10,60 €");

        productLikeBtn.setBackground(new java.awt.Color(179, 110, 120));
        productLikeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productLikeBtn.setText("Buy");

        productPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/wineImage.png"))); // NOI18N
        productPhoto.setText(" ");

        productBuyBtn.setBackground(new java.awt.Color(179, 110, 120));
        productBuyBtn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        productBuyBtn.setForeground(new java.awt.Color(255, 255, 255));
        productBuyBtn.setText("♡");

        javax.swing.GroupLayout productBoxContLayout = new javax.swing.GroupLayout(productBoxCont);
        productBoxCont.setLayout(productBoxContLayout);
        productBoxContLayout.setHorizontalGroup(
            productBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productBoxContLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(productBoxContLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(productPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(productInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(productBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productLikeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productBuyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        productBoxContLayout.setVerticalGroup(
            productBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productBoxContLayout.createSequentialGroup()
                .addGroup(productBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productBoxContLayout.createSequentialGroup()
                        .addGroup(productBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productBoxContLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(productTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(productInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBoxContLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productBuyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(productBoxContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productPrice)
                            .addComponent(productLikeBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBoxContLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productPhoto)))
                .addContainerGap())
        );

        productBoxPanel.add(productBoxCont);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel productBoxCont;
    private javax.swing.JPanel productBoxPanel;
    private javax.swing.JButton productBuyBtn;
    private javax.swing.JLabel productInfo;
    private javax.swing.JButton productLikeBtn;
    private javax.swing.JLabel productPhoto;
    private javax.swing.JLabel productPrice;
    private javax.swing.JLabel productTitle;
    // End of variables declaration//GEN-END:variables
}
