/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package winepackage;

/**
 *
 * @author dimitris
 */
public class ProductSquerePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductSquerePanel
     */
    public ProductSquerePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productSquerePanel = new javax.swing.JPanel();
        descriptionSquerePanel = new javax.swing.JPanel();
        titleSquere = new javax.swing.JLabel();
        infoSquere = new javax.swing.JLabel();
        priceSquere = new javax.swing.JLabel();
        buyButtonSquere = new javax.swing.JButton();
        likeButtonSquere = new javax.swing.JButton();
        photoCodeSquere = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        productSquerePanel.setBackground(new java.awt.Color(255, 255, 255));

        descriptionSquerePanel.setBackground(new java.awt.Color(255, 255, 255));

        titleSquere.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleSquere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSquere.setText("Zero Sauvignon Blanc");

        infoSquere.setForeground(new java.awt.Color(51, 51, 51));
        infoSquere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoSquere.setText("Ξηρός, Ήπιος, Λευκός");

        priceSquere.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        priceSquere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceSquere.setText("10,60 €");

        buyButtonSquere.setBackground(new java.awt.Color(179, 110, 120));
        buyButtonSquere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buyButtonSquere.setText("Buy");

        likeButtonSquere.setBackground(new java.awt.Color(179, 110, 120));
        likeButtonSquere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        likeButtonSquere.setText("♡");
        likeButtonSquere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeButtonSquereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout descriptionSquerePanelLayout = new javax.swing.GroupLayout(descriptionSquerePanel);
        descriptionSquerePanel.setLayout(descriptionSquerePanelLayout);
        descriptionSquerePanelLayout.setHorizontalGroup(
            descriptionSquerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionSquerePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descriptionSquerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleSquere, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(infoSquere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(descriptionSquerePanelLayout.createSequentialGroup()
                        .addComponent(priceSquere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(likeButtonSquere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buyButtonSquere, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        descriptionSquerePanelLayout.setVerticalGroup(
            descriptionSquerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionSquerePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleSquere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoSquere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(descriptionSquerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceSquere)
                    .addComponent(buyButtonSquere)
                    .addComponent(likeButtonSquere))
                .addContainerGap())
        );

        photoCodeSquere.setBackground(new java.awt.Color(255, 255, 255));
        photoCodeSquere.setForeground(new java.awt.Color(255, 255, 255));
        photoCodeSquere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoCodeSquere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/winepackage/images/wineImage.png"))); // NOI18N
        photoCodeSquere.setText(" ");

        javax.swing.GroupLayout productSquerePanelLayout = new javax.swing.GroupLayout(productSquerePanel);
        productSquerePanel.setLayout(productSquerePanelLayout);
        productSquerePanelLayout.setHorizontalGroup(
            productSquerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionSquerePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productSquerePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photoCodeSquere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        productSquerePanelLayout.setVerticalGroup(
            productSquerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productSquerePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photoCodeSquere, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(descriptionSquerePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productSquerePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productSquerePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTitleSquere(String title) {
        titleSquere.setText(title);
    }

    public void setPriceSquere(String price) {
        priceSquere.setText(price);
    }

    public void setinfoSquere(String info) {
        infoSquere.setText(info);
    }
    
    public void setImageSquere(String photoCode){
        String loc = "/winepackage/images/" + "1" + ".png";
        photoCodeSquere.setIcon(new javax.swing.ImageIcon(getClass().getResource(loc)));
    }

    
    private void likeButtonSquereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeButtonSquereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likeButtonSquereActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButtonSquere;
    private javax.swing.JPanel descriptionSquerePanel;
    public javax.swing.JLabel infoSquere;
    private javax.swing.JButton likeButtonSquere;
    public javax.swing.JLabel photoCodeSquere;
    public javax.swing.JLabel priceSquere;
    private javax.swing.JPanel productSquerePanel;
    public javax.swing.JLabel titleSquere;
    // End of variables declaration//GEN-END:variables
}
